version: '3'

services:
    swagger-ui:
        image: swaggerapi/swagger-ui
        container_name: swagger_ui
        ports:
            - "8000:8080"
        volumes:
            - ./doc:/usr/share/nginx/html/doc
        environment:
            URLS: "[{ url: \"doc/latest/.yaml\", name: \"latest\"},
                    { url: \"doc/v1.0.0/.yaml\", name: \"v1.0.0\"},
                    { url: \"doc/v1.0.1/.yaml\", name: \"v1.0.1\"},
                ]"
