openapi: 3.0.0
info:
  title: API documentation
  version: latest
servers:
  - url: http://gypark.gifty4u.com
paths:
  /v1.0.0/login:
    $ref: '../v1.0.0/.yaml#/paths/~1login'
  /v1.0.1/prices:
    $ref: '../v1.0.1/.yaml#/paths/~1prices'

components:
  securitySchemes:
    BearerAuth:
      $ref: '../v1.0.0/schemas/security.yaml'
